export const transactionsData = [
  {
    "Row ID": 536,
    "Order ID": "CA-2017-126613",
    "Order Date": "10/07/2017",
    "Ship Date": "16/07/2017",
    "Ship Mode": "Standard Class",
    "Customer ID": "AA-10375",
    "Customer Name": "Allen Armold",
    Segment: "Consumer",
    Country: "United States",
    City: "Mesa",
    State: "Arizona",
    "Postal Code": 85204,
    Region: "West",
    "Product ID": "OFF-ST-10001325",
    Category: "Office Supplies",
    "Sub-Category": "Storage",
    "Product Name": "Sterilite Officeware Hinged File Box",
    Sales: 16.768,
  },
  {
    "Row ID": 557,
    "Order ID": "CA-2017-113243",
    "Order Date": "10/06/2017",
    "Ship Date": "15/06/2017",
    "Ship Mode": "Standard Class",
    "Customer ID": "OT-18730",
    "Customer Name": "Olvera Toch",
    Segment: "Consumer",
    Country: "United States",
    City: "Los Angeles",
    State: "California",
    "Postal Code": 90045,
    Region: "West",
    "Product ID": "OFF-LA-10001297",
    Category: "Office Supplies",
    "Sub-Category": "Labels",
    "Product Name": "Avery 473",
    Sales: 20.7,
  },
  {
    "Row ID": 558,
    "Order ID": "CA-2017-113243",
    "Order Date": "10/06/2017",
    "Ship Date": "15/06/2017",
    "Ship Mode": "Standard Class",
    "Customer ID": "OT-18730",
    "Customer Name": "Olvera Toch",
    Segment: "Consumer",
    Country: "United States",
    City: "Los Angeles",
    State: "California",
    "Postal Code": 90045,
    Region: "West",
    "Product ID": "FUR-TA-10004256",
    Category: "Furniture",
    "Sub-Category": "Tables",
    "Product Name":
      "Bretford “Just In Time” Height-Adjustable Multi-Task Work Tables",
    Sales: 1335.68,
  },
  {
    "Row ID": 559,
    "Order ID": "CA-2017-113243",
    "Order Date": "10/06/2017",
    "Ship Date": "15/06/2017",
    "Ship Mode": "Standard Class",
    "Customer ID": "OT-18730",
    "Customer Name": "Olvera Toch",
    Segment: "Consumer",
    Country: "United States",
    City: "Los Angeles",
    State: "California",
    "Postal Code": 90045,
    Region: "West",
    "Product ID": "OFF-PA-10003441",
    Category: "Office Supplies",
    "Sub-Category": "Paper",
    "Product Name": "Xerox 226",
    Sales: 32.4,
  },
  {
    "Row ID": 1412,
    "Order ID": "CA-2017-136329",
    "Order Date": "09/07/2017",
    "Ship Date": "13/07/2017",
    "Ship Mode": "Standard Class",
    "Customer ID": "JD-15895",
    "Customer Name": "Jonathan Doherty",
    Segment: "Corporate",
    Country: "United States",
    City: "New York City",
    State: "New York",
    "Postal Code": 10035,
    Region: "East",
    "Product ID": "FUR-CH-10002335",
    Category: "Furniture",
    "Sub-Category": "Chairs",
    "Product Name": "Hon GuestStacker Chair",
    Sales: 408.006,
  },
  {
    "Row ID": 1413,
    "Order ID": "CA-2017-136329",
    "Order Date": "09/07/2017",
    "Ship Date": "13/07/2017",
    "Ship Mode": "Standard Class",
    "Customer ID": "JD-15895",
    "Customer Name": "Jonathan Doherty",
    Segment: "Corporate",
    Country: "United States",
    City: "New York City",
    State: "New York",
    "Postal Code": 10035,
    Region: "East",
    "Product ID": "FUR-FU-10000723",
    Category: "Furniture",
    "Sub-Category": "Furnishings",
    "Product Name":
      "Deflect-o EconoMat Studded, No Bevel Mat for Low Pile Carpeting",
    Sales: 165.28,
  },
  {
    "Row ID": 1733,
    "Order ID": "US-2017-131149",
    "Order Date": "10/07/2017",
    "Ship Date": "14/07/2017",
    "Ship Mode": "Standard Class",
    "Customer ID": "LH-17155",
    "Customer Name": "Logan Haushalter",
    Segment: "Consumer",
    Country: "United States",
    City: "Dallas",
    State: "Texas",
    "Postal Code": 75081,
    Region: "Central",
    "Product ID": "OFF-ST-10000689",
    Category: "Office Supplies",
    "Sub-Category": "Storage",
    "Product Name": "Fellowes Strictly Business Drawer File, Letter/Legal Size",
    Sales: 338.04,
  },
  {
    "Row ID": 1734,
    "Order ID": "US-2017-131149",
    "Order Date": "10/07/2017",
    "Ship Date": "14/07/2017",
    "Ship Mode": "Standard Class",
    "Customer ID": "LH-17155",
    "Customer Name": "Logan Haushalter",
    Segment: "Consumer",
    Country: "United States",
    City: "Dallas",
    State: "Texas",
    "Postal Code": 75081,
    Region: "Central",
    "Product ID": "OFF-AR-10002135",
    Category: "Office Supplies",
    "Sub-Category": "Art",
    "Product Name": "Boston Heavy-Duty Trimline Electric Pencil Sharpeners",
    Sales: 154.24,
  },
  {
    "Row ID": 1927,
    "Order ID": "US-2017-139710",
    "Order Date": "09/06/2017",
    "Ship Date": "15/06/2017",
    "Ship Mode": "Standard Class",
    "Customer ID": "GM-14680",
    "Customer Name": "Greg Matthias",
    Segment: "Consumer",
    Country: "United States",
    City: "Los Angeles",
    State: "California",
    "Postal Code": 90045,
    Region: "West",
    "Product ID": "TEC-PH-10001198",
    Category: "Technology",
    "Sub-Category": "Phones",
    "Product Name": "Avaya 4621SW VoIP phone",
    Sales: 177.48,
  },
  {
    "Row ID": 2428,
    "Order ID": "CA-2017-169922",
    "Order Date": "11/06/2017",
    "Ship Date": "17/06/2017",
    "Ship Mode": "Standard Class",
    "Customer ID": "MZ-17515",
    "Customer Name": "Mary Zewe",
    Segment: "Corporate",
    Country: "United States",
    City: "Arlington",
    State: "Texas",
    "Postal Code": 76017,
    Region: "Central",
    "Product ID": "OFF-BI-10003784",
    Category: "Office Supplies",
    "Sub-Category": "Binders",
    "Product Name": "Computer Printout Index Tabs",
    Sales: 1.344,
  },
  {
    "Row ID": 2429,
    "Order ID": "CA-2017-169922",
    "Order Date": "11/06/2017",
    "Ship Date": "17/06/2017",
    "Ship Mode": "Standard Class",
    "Customer ID": "MZ-17515",
    "Customer Name": "Mary Zewe",
    Segment: "Corporate",
    Country: "United States",
    City: "Arlington",
    State: "Texas",
    "Postal Code": 76017,
    Region: "Central",
    "Product ID": "OFF-BI-10001617",
    Category: "Office Supplies",
    "Sub-Category": "Binders",
    "Product Name": "GBC Wire Binding Combs",
    Sales: 8.272,
  },
  {
    "Row ID": 2430,
    "Order ID": "CA-2017-169922",
    "Order Date": "11/06/2017",
    "Ship Date": "17/06/2017",
    "Ship Mode": "Standard Class",
    "Customer ID": "MZ-17515",
    "Customer Name": "Mary Zewe",
    Segment: "Corporate",
    Country: "United States",
    City: "Arlington",
    State: "Texas",
    "Postal Code": 76017,
    Region: "Central",
    "Product ID": "FUR-FU-10004415",
    Category: "Furniture",
    "Sub-Category": "Furnishings",
    "Product Name": "Stacking Tray, Side-Loading, Legal, Smoke",
    Sales: 12.544,
  },
  {
    "Row ID": 2758,
    "Order ID": "CA-2017-127775",
    "Order Date": "11/06/2017",
    "Ship Date": "13/06/2017",
    "Ship Mode": "Second Class",
    "Customer ID": "ES-14020",
    "Customer Name": "Erica Smith",
    Segment: "Consumer",
    Country: "United States",
    City: "New York City",
    State: "New York",
    "Postal Code": 10035,
    Region: "East",
    "Product ID": "TEC-AC-10002402",
    Category: "Technology",
    "Sub-Category": "Accessories",
    "Product Name": "Razer Kraken PRO Over Ear PC and Music Headset",
    Sales: 239.97,
  },
  {
    "Row ID": 2839,
    "Order ID": "CA-2017-147368",
    "Order Date": "09/06/2017",
    "Ship Date": "12/06/2017",
    "Ship Mode": "First Class",
    "Customer ID": "TC-21295",
    "Customer Name": "Toby Carlisle",
    Segment: "Consumer",
    Country: "United States",
    City: "Tallahassee",
    State: "Florida",
    "Postal Code": 32303,
    Region: "South",
    "Product ID": "TEC-MA-10002178",
    Category: "Technology",
    "Sub-Category": "Machines",
    "Product Name": "Cisco CP-7937G Unified IP Conference Station Phone",
    Sales: 695.7,
  },
  {
    "Row ID": 3517,
    "Order ID": "US-2017-113649",
    "Order Date": "09/08/2017",
    "Ship Date": "12/08/2017",
    "Ship Mode": "First Class",
    "Customer ID": "HA-14920",
    "Customer Name": "Helen Andreada",
    Segment: "Consumer",
    Country: "United States",
    City: "Fayetteville",
    State: "North Carolina",
    "Postal Code": 28314,
    Region: "South",
    "Product ID": "OFF-PA-10000130",
    Category: "Office Supplies",
    "Sub-Category": "Paper",
    "Product Name": "Xerox 199",
    Sales: 30.816,
  },
  {
    "Row ID": 3518,
    "Order ID": "US-2017-113649",
    "Order Date": "09/08/2017",
    "Ship Date": "12/08/2017",
    "Ship Mode": "First Class",
    "Customer ID": "HA-14920",
    "Customer Name": "Helen Andreada",
    Segment: "Consumer",
    Country: "United States",
    City: "Fayetteville",
    State: "North Carolina",
    "Postal Code": 28314,
    Region: "South",
    "Product ID": "TEC-PH-10002350",
    Category: "Technology",
    "Sub-Category": "Phones",
    "Product Name": "Apple EarPods with Remote and Mic",
    Sales: 44.784,
  },
  {
    "Row ID": 3519,
    "Order ID": "US-2017-113649",
    "Order Date": "09/08/2017",
    "Ship Date": "12/08/2017",
    "Ship Mode": "First Class",
    "Customer ID": "HA-14920",
    "Customer Name": "Helen Andreada",
    Segment: "Consumer",
    Country: "United States",
    City: "Fayetteville",
    State: "North Carolina",
    "Postal Code": 28314,
    Region: "South",
    "Product ID": "OFF-AP-10002518",
    Category: "Office Supplies",
    "Sub-Category": "Appliances",
    "Product Name": "Kensington 7 Outlet MasterPiece Power Center",
    Sales: 569.536,
  },
  {
    "Row ID": 3520,
    "Order ID": "CA-2017-326613",
    "Order Date": "08/08/2017",
    "Ship Date": "16/08/2017",
    "Ship Mode": "Standard Class",
    "Customer ID": "AA-10375",
    "Customer Name": "Allen Armold",
    Segment: "Consumer",
    Country: "United States",
    City: "Mesa",
    State: "Arizona",
    "Postal Code": 85204,
    Region: "West",
    "Product ID": "OFF-ST-10001325",
    Category: "Office Supplies",
    "Sub-Category": "Storage",
    "Product Name": "Sterilite Officeware Hinged File Box",
    Sales: 90.768,
  },
   {
    "Row ID": 3521,
    "Order ID": "US-2017-113649",
    "Order Date": "12/09/2017",
    "Ship Date": "12/08/2017",
    "Ship Mode": "First Class",
    "Customer ID": "HA-14920",
    "Customer Name": "Helen Andreada",
    Segment: "Consumer",
    Country: "United States",
    City: "Fayetteville",
    State: "North Carolina",
    "Postal Code": 28314,
    Region: "South",
    "Product ID": "OFF-AP-10002518",
    Category: "Office Supplies",
    "Sub-Category": "Appliances",
    "Product Name": "Kensington 7 Outlet MasterPiece Power Center",
    Sales: 142.36,
  },
];
